import { avatarsImages } from '../avatars';

export const cardsCharacters =[
    {name:'Alastor', img: avatarsImages.Alastor, key :1},
    {name:'Argus', img: avatarsImages.Argus, key :2},
    {name:'Bellatriz', img: avatarsImages.Bellatrix, key :3},
    {name:'Cedric', img: avatarsImages.Cedric, key :4},
    {name:'Dobby', img: avatarsImages.Dobby, key :5},
    {name:'Draco', img: avatarsImages.Draco, key :6},
    {name:'Dumbledor', img: avatarsImages.Dumbledor, key :7},
    {name:'Fleur', img: avatarsImages.Fleur, key :8},
    {name:'Ginny', img: avatarsImages.Ginny, key :9},
    {name:'Harry', img: avatarsImages.Harry, key :10},
    {name:'Hedwig', img: avatarsImages.Hedwig, key :11},
    {name:'Hermione', img: avatarsImages.Hermmione, key :12},
    {name:'Voldemort', img: avatarsImages.LordVoldemort, key :13},
    {name:'Luna', img: avatarsImages.LunaLovegood, key :14},
    {name:'Minerva', img: avatarsImages.Minerva, key :15},
    {name:'Myrtle', img: avatarsImages.Myrtle, key :16},
    {name:'Nagini', img: avatarsImages.Nagini, key :17},
    {name:'Pettigrew', img: avatarsImages.PeterPetttigrew, key :18},
    {name:'Ron', img: avatarsImages.Ron, key :19},
    {name:'Hagrid', img: avatarsImages.RubeusHagrid, key :20},
    {name:'Severus', img: avatarsImages.Severus, key :21},
    {name:'Sombrero', img: avatarsImages.Sombrero, key :22},
    {name:'Umbridge', img: avatarsImages.Umbridge, key:23},
    {name:'Anillo', img:avatarsImages.Anillo, key:24},
    {name:'Bugby', img:avatarsImages.Bugby, key:25},
    {name:'Caldero', img:avatarsImages.Caldero, key:26},
    {name:'Capa', img:avatarsImages.Capa, key:27},
    {name:'Cho', img:avatarsImages.Cho, key:28},
    {name:'Copahuff', img:avatarsImages.Copahuff, key:29},
    {name:'Diadema', img:avatarsImages.Diadema, key:30},
    {name:'Diario', img:avatarsImages.Diario, key:31},
    {name:'Dudley', img:avatarsImages.Dudley, key:32},
    {name:'Fluffy', img:avatarsImages.Flyffy, key:33},
    {name:'Grindylow', img:avatarsImages.Grindylow, key:34},
    {name:'Guardapelo', img:avatarsImages.Guardapelo, key:35},
    {name:'Lentes', img:avatarsImages.Lentes, key:36},
    {name:'Lucius', img:avatarsImages.Lucius, key:37},
    {name:'Neville', img:avatarsImages.Neville, key:38},
    {name:'Nimbus', img:avatarsImages.Nimbus, key:39},
    {name:'Petunia', img:avatarsImages.Petunia, key:40},
    {name:'Piedra', img:avatarsImages.Piedra, key:41},
    {name:'Remus', img:avatarsImages.Remus, key:42},
    {name:'Sauco', img:avatarsImages.Sauco, key:43},
    {name:'Sirius', img:avatarsImages.Sirius, key:44},
    {name:'Sybill', img:avatarsImages.Sybill, key:45},
    {name:'Viktor', img:avatarsImages.Viktor, key:46},
]